import { withAlpha } from "@/lib/brandColor";
import { useState, type FormEvent } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { useMeta } from "@/hooks/useMeta";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { motion } from "framer-motion";
import { Link } from "wouter";
import {
  Shield,
  CheckCircle,
  Clock,
  FlaskConical,
  Download,
  Instagram,
  MessageSquare,
  Flame,
  Calendar,
  Camera,
  NotebookPen,
  Lock,
  Music2,
  Briefcase,
  Send,
  ArrowRight,
  Sparkles,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useJoinWaitlist } from "@workspace/api-client-react";

type Status = "live" | "coming" | "researching";

type IntegrationCard = {
  title: string;
  icon: typeof Flame;
  color: string;
  blurb: string;
  bullets?: string[];
  access?: string[];
  excludes?: string[];
  privacy?: string;
  link?: { href: string; label: string };
};

const STATUS_META: Record<Status, { label: string; color: string }> = {
  live: { label: "Live", color: "hsl(142 55% 60%)" },
  coming: { label: "Coming Q3 2026", color: "hsl(var(--brand-indigo))" },
  researching: { label: "Researching", color: "hsl(43 65% 65%)" },
};

const CONNECTED: IntegrationCard[] = [
  {
    title: "Hinge GDPR ZIP import",
    icon: Flame,
    color: "hsl(348 75% 60%)",
    blurb:
      "Export your full Hinge data from the app (Settings, Download My Data), drop the ZIP in, and we read your prompts, likes, and matches to build a real signal map. No login required, no API needed.",
    privacy:
      "Read only. Never posts. Encrypted at rest. If Deep AI lane is on in Settings, the import summary is generated by Anthropic Claude under their zero-retention API policy. Off means a deterministic summary instead. We never sell or train on your content. Delete the parsed data in one click from your vault.",
  },
  {
    title: "Instagram tone paste",
    icon: Instagram,
    color: "hsl(326 70% 60%)",
    blurb:
      "Paste your three most recent captions. We compare your IG voice to your dating-app voice and flag where the two are saying different things about who you are.",
    privacy:
      "Read only. Pasted text only. No API call to Meta, no login, no follower list. If Deep AI lane is on, tone extraction runs through Anthropic Claude under their zero-retention API policy. Off means the deterministic extractor handles it.",
  },
  {
    title: "Manual message paste",
    icon: MessageSquare,
    color: "hsl(248 62% 60%)",
    blurb:
      "Paste a recent thread from any app (Hinge, Bumble, Tinder, Grindr, Feeld, HER, iMessage screenshots transcribed). Chemistry Lab returns five reply options scored by warmth, directness, and date-pacing.",
    privacy:
      "Session only by default. Encrypted at rest if you save. Counterparty identifiers are stripped before storage. If Deep AI lane is on, reply options are generated by Anthropic Claude under their zero-retention API policy. Off means deterministic reply options.",
  },
];

const COMING: IntegrationCard[] = [
  {
    title: "Hinge OAuth",
    icon: Flame,
    color: "hsl(348 75% 60%)",
    blurb:
      "When Hinge opens a developer API, we plug in for live profile sync and match-pacing analytics. We are tracking their public partnership roadmap.",
    access: ["Your own profile text and prompts", "Your match list (no profiles of others without consent)", "Your conversation activity (counts and timestamps)"],
    excludes: ["The full bios or photos of people who didn't opt in", "Anything outside your own account", "Anything Match Group hasn't explicitly authorised"],
    link: { href: "https://mtch.com/news", label: "Match Group partnerships news" },
  },
  {
    title: "Tinder OAuth",
    icon: Flame,
    color: "hsl(8 80% 55%)",
    blurb:
      "Same shape as Hinge OAuth. Live profile sync, swipe-pacing analytics, plus a daily nudge if your reply latency is hurting matches.",
    access: ["Your profile fields", "Your swipe and match counts", "Your message activity on your own account"],
    excludes: ["Other people's profile data beyond what you've already matched with", "Anything the Tinder API doesn't surface to the account owner"],
  },
  {
    title: "Bumble OAuth",
    icon: Flame,
    color: "hsl(43 90% 55%)",
    blurb:
      "Live profile sync plus the 24-hour reply window: we'll surface threads about to expire and draft a low-pressure follow-up.",
    access: ["Your profile content", "Your active match list and reply-window state", "Aggregate stats on your own account"],
    excludes: ["Other accounts' data", "Anything the Bumble API doesn't surface to the account owner"],
  },
  {
    title: "Google Calendar",
    icon: Calendar,
    color: "hsl(212 70% 55%)",
    blurb:
      "Pacing insights. If you tag an event 'date', we'll prep you the night before with a 90-second brief, and after, we'll prompt a short debrief while it's still fresh.",
    access: ["Event title and time on events you explicitly tag", "Tagged event status (cancelled, moved, kept)"],
    excludes: ["Work meetings", "Untagged personal events", "Attendees and locations"],
  },
  {
    title: "Instagram Graph API",
    icon: Instagram,
    color: "hsl(326 70% 60%)",
    blurb:
      "Once Meta's Graph API opens for personal accounts at the level we need, tone extraction happens automatically instead of via paste.",
    access: ["Your public captions and bio", "Your public post cadence"],
    excludes: ["DMs", "Stories", "Followers and following lists", "Insights and reach data"],
  },
  {
    title: "Apple Photos",
    icon: Camera,
    color: "hsl(200 15% 50%)",
    blurb:
      "Photo audit without upload. On-device analysis through Apple's PhotosKit and Core ML for composition, expression variety, and group-shot density. Your photos never leave the device.",
    access: ["On-device EXIF and composition scoring on photos you select"],
    excludes: ["Any photo upload to our servers", "Photos you didn't pick", "Faces of people other than you"],
  },
  {
    title: "Notion",
    icon: NotebookPen,
    color: "hsl(0 0% 60%)",
    blurb:
      "Export your dating second brain. Push your audits, journal entries, debriefs, and pattern reads to a dated Notion database you own.",
    access: ["A database in your Notion workspace that you create and authorise"],
    excludes: ["Any other Notion page or workspace", "Read access to your existing content"],
  },
];

const RESEARCHING: IntegrationCard[] = [
  {
    title: "WhatsApp and iMessage",
    icon: MessageSquare,
    color: "hsl(142 55% 55%)",
    blurb:
      "End-to-end encrypted by design. We're researching local on-device processing so message tone analysis can happen without anything leaving your phone. Open research question: can we deliver useful coaching while honouring the E2EE contract.",
  },
  {
    title: "LinkedIn",
    icon: Briefcase,
    color: "hsl(207 70% 45%)",
    blurb:
      "Career compatibility is real signal. Research question: how do we surface it without turning the app into a recruiter tool, and how do we get there without LinkedIn's API gating us out.",
  },
  {
    title: "Spotify",
    icon: Music2,
    color: "hsl(141 73% 42%)",
    blurb:
      "Music taste overlap predicts conversation chemistry better than most prompt answers. Opt-in only, with a clear toggle. Research question: which signal is durable (top artists, listening cadence, genre diversity) and which is noise.",
  },
];

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 20 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.5, delay, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] },
});

function StatusBadge({ status }: { status: Status }) {
  const meta = STATUS_META[status];
  return (
    <span
      className="inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full"
      style={{
        background: withAlpha(meta.color, 0.12),
        color: meta.color,
        border: `1px solid ${withAlpha(meta.color, 0.3)}`,
      }}
      data-testid={`badge-status-${status}`}
    >
      {status === "live" && <span className="w-1.5 h-1.5 rounded-full" style={{ background: meta.color }} />}
      {meta.label}
    </span>
  );
}

function Card({ card, status, index }: { card: IntegrationCard; status: Status; index: number }) {
  const testId = `card-${status}-${card.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`;
  return (
    <motion.div
      {...fadeUp(0.04 + index * 0.04)}
      className="glass border border-white/8 rounded-2xl p-5 flex flex-col gap-3 hover:border-white/15 transition-colors"
      data-testid={testId}
    >
      <div className="flex items-start gap-3">
        <div
          className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
          style={{ background: withAlpha(card.color, 0.14), border: `1px solid ${withAlpha(card.color, 0.25)}` }}
        >
          <card.icon className="w-5 h-5" style={{ color: card.color }} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap mb-1">
            <p className="font-semibold text-foreground text-sm leading-snug">{card.title}</p>
            <StatusBadge status={status} />
          </div>
          <p className="text-xs text-muted-foreground leading-relaxed">{card.blurb}</p>
        </div>
      </div>

      {card.privacy && (
        <div className="flex items-start gap-2 rounded-xl bg-white/3 border border-white/6 px-3 py-2.5">
          <Shield className="w-3.5 h-3.5 text-[hsl(142_55%_60%)] flex-shrink-0 mt-0.5" />
          <p className="text-[11px] text-muted-foreground/80 leading-relaxed">
            <strong className="text-foreground/75">Privacy: </strong>
            {card.privacy}
          </p>
        </div>
      )}

      {(card.access || card.excludes) && (
        <div className="grid sm:grid-cols-2 gap-2.5 mt-1">
          {card.access && (
            <div className="rounded-xl border border-[hsl(142_55%_60%/0.2)] bg-[hsl(142_55%_45%/0.06)] p-3">
              <p className="text-[10px] font-bold uppercase tracking-wider text-[hsl(142_55%_62%)] mb-1.5 flex items-center gap-1.5">
                <CheckCircle className="w-3 h-3" /> What we'll access
              </p>
              <ul className="space-y-1">
                {card.access.map((item) => (
                  <li key={item} className="text-[11px] text-muted-foreground leading-snug flex gap-1.5">
                    <span className="w-1 h-1 rounded-full bg-[hsl(142_55%_60%)] mt-1.5 flex-shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {card.excludes && (
            <div className="rounded-xl border border-[hsl(348_55%_65%/0.2)] bg-[hsl(348_55%_55%/0.06)] p-3">
              <p className="text-[10px] font-bold uppercase tracking-wider text-[hsl(348_55%_72%)] mb-1.5 flex items-center gap-1.5">
                <Lock className="w-3 h-3" /> What we won't
              </p>
              <ul className="space-y-1">
                {card.excludes.map((item) => (
                  <li key={item} className="text-[11px] text-muted-foreground leading-snug flex gap-1.5">
                    <span className="w-1 h-1 rounded-full bg-[hsl(348_55%_65%)] mt-1.5 flex-shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {card.link && (
        <a
          href={card.link.href}
          target="_blank"
          rel="noopener noreferrer"
          className="text-[11px] font-semibold text-[hsl(248_62%_65%)] hover:text-[hsl(248_62%_75%)] inline-flex items-center gap-1 self-start"
        >
          {card.link.label} <ArrowRight className="w-3 h-3" />
        </a>
      )}
    </motion.div>
  );
}

function SectionHeader({
  icon: Icon,
  eyebrow,
  title,
  subtitle,
  accent,
}: {
  icon: typeof Flame;
  eyebrow: string;
  title: string;
  subtitle: string;
  accent: string;
}) {
  return (
    <div className="mb-5">
      <div className="flex items-center gap-2 mb-2">
        <div
          className="w-7 h-7 rounded-lg flex items-center justify-center"
          style={{ background: withAlpha(accent, 0.14), border: `1px solid ${withAlpha(accent, 0.25)}` }}
        >
          <Icon className="w-3.5 h-3.5" style={{ color: accent }} />
        </div>
        <p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: accent }}>{eyebrow}</p>
      </div>
      <h2 className="text-xl sm:text-2xl font-bold text-foreground">{title}</h2>
      <p className="text-sm text-muted-foreground mt-1 leading-relaxed">{subtitle}</p>
    </div>
  );
}

function RequestForm() {
  const { toast } = useToast();
  const [firstName, setFirstName] = useState("");
  const [email, setEmail] = useState("");
  const [platform, setPlatform] = useState("");
  const [why, setWhy] = useState("");
  const [submitted, setSubmitted] = useState(false);

  // Integration requests are routed through the existing waitlist endpoint
  // (interestedIn carries the platform + reason). We intentionally avoid
  // standing up a dedicated endpoint until volume justifies the schema.
  const { mutate: joinWaitlist, isPending } = useJoinWaitlist();

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!email.includes("@") || platform.trim().length === 0) return;
    joinWaitlist(
      {
        data: {
          email: email.trim(),
          firstName: firstName.trim() || "Friend",
          podcastSource: "integration-request",
          interestedIn: `Platform: ${platform.trim()}${why.trim() ? ` | Why: ${why.trim()}` : ""}`,
        },
      },
      {
        onSuccess: () => {
          setSubmitted(true);
          toast({
            title: "Request logged",
            description: "We'll tell you the day it ships.",
          });
        },
        onError: () => {
          toast({
            title: "Couldn't send that",
            description: "Try again in a moment.",
            variant: "destructive",
          });
        },
      },
    );
  }

  if (submitted) {
    return (
      <div
        className="rounded-2xl border p-6 text-center"
        style={{ background: "hsl(142 55% 45% / 0.06)", borderColor: "hsl(142 55% 60% / 0.3)" }}
        data-testid="integration-request-success"
      >
        <CheckCircle className="w-7 h-7 text-[hsl(142_55%_60%)] mx-auto mb-2" />
        <p className="font-semibold text-foreground">Got it, {firstName || "friend"}.</p>
        <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
          Your request for <strong className="text-foreground/80">{platform}</strong> is in. We'll email you the day it ships.
        </p>
      </div>
    );
  }

  return (
    <form
      onSubmit={handleSubmit}
      className="glass border border-white/10 rounded-2xl p-5 sm:p-6 space-y-4"
      data-testid="form-integration-request"
    >
      <div>
        <p className="font-semibold text-foreground text-sm">Request an integration</p>
        <p className="text-xs text-muted-foreground mt-0.5">
          Tell us the platform you want next. We'll log it against demand and email you the day it lands.
        </p>
      </div>
      <div className="grid sm:grid-cols-2 gap-3">
        <div>
          <label className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/70 mb-1.5 block">
            First name
          </label>
          <Input
            value={firstName}
            onChange={(e) => setFirstName(e.target.value)}
            placeholder="Jordan"
            data-testid="input-integration-firstname"
          />
        </div>
        <div>
          <label className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/70 mb-1.5 block">
            Email
          </label>
          <Input
            type="email"
            required
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="you@example.com"
            data-testid="input-integration-email"
          />
        </div>
      </div>
      <div>
        <label className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/70 mb-1.5 block">
          Platform <span className="text-[hsl(248_62%_62%)]">*</span>
        </label>
        <Input
          required
          value={platform}
          onChange={(e) => setPlatform(e.target.value)}
          placeholder="Feeld, OkCupid, Strava, your dating spreadsheet, anything"
          data-testid="input-integration-platform"
        />
      </div>
      <div>
        <label className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/70 mb-1.5 block">
          Why this matters to you (optional)
        </label>
        <Textarea
          value={why}
          onChange={(e) => setWhy(e.target.value)}
          placeholder="What signal would it surface that nothing else does?"
          className="min-h-[90px] resize-none"
          data-testid="textarea-integration-why"
        />
      </div>
      <div className="flex items-center justify-between gap-3 flex-wrap pt-1">
        <p className="text-[11px] text-muted-foreground/60">
          We use this to prioritise the roadmap. No marketing list.
        </p>
        <Button
          type="submit"
          disabled={isPending}
          className="rounded-full bg-gradient-to-r from-[#3D35CC] to-[#FF2D9B] border-0 font-semibold"
          data-testid="button-submit-integration-request"
        >
          <Send className="w-3.5 h-3.5 mr-2" />
          {isPending ? "Sending..." : "Send request"}
        </Button>
      </div>
    </form>
  );
}

export default function Integrations() {
  useMeta(
    "Platform Map",
    "What MatchLab Club is connected to today, what's coming, and what works right now via paste. Consent-first, read only, encrypted at rest.",
  );

  return (
    <AppLayout>
      <div className="min-h-screen mesh-bg py-10 px-4">
        <div className="orb orb-violet fixed w-[420px] h-[420px] -top-24 -right-16 opacity-30 pointer-events-none" />
        <div className="orb orb-gold fixed w-[300px] h-[300px] bottom-10 -left-20 opacity-25 pointer-events-none" />

        <div className="max-w-4xl mx-auto relative z-10">
          {/* Hero */}
          <motion.div {...fadeUp(0)} className="mb-10 text-center sm:text-left">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass border border-[hsl(248_62%_52%/0.25)] mb-4">
              <Sparkles className="w-3.5 h-3.5 text-[hsl(248_62%_62%)]" />
              <span className="text-[11px] font-semibold uppercase tracking-wider text-[hsl(248_62%_62%)]">Platform Map</span>
            </div>
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-foreground tracking-tight">
              Every connection, every promise.
            </h1>
            <p className="text-base text-muted-foreground mt-3 max-w-2xl leading-relaxed">
              What we're connected to, what's coming, and what works today via paste. One page, no marketing fog.
            </p>
          </motion.div>

          {/* Quick legend */}
          <motion.div {...fadeUp(0.05)} className="flex flex-wrap items-center gap-2 mb-10">
            <StatusBadge status="live" />
            <span className="text-[11px] text-muted-foreground">Shipping today.</span>
            <span className="text-white/15">·</span>
            <StatusBadge status="coming" />
            <span className="text-[11px] text-muted-foreground">Built when the platform opens its API.</span>
            <span className="text-white/15">·</span>
            <StatusBadge status="researching" />
            <span className="text-[11px] text-muted-foreground">Open question. Real research in progress.</span>
          </motion.div>

          {/* Connected (live) */}
          <section className="mb-12">
            <SectionHeader
              icon={CheckCircle}
              eyebrow="Connected today"
              title="What works right now"
              subtitle="No API required. No login dance. Each of these is in the product today."
              accent="hsl(142 55% 60%)"
            />
            <div className="grid gap-4">
              {CONNECTED.map((card, i) => (
                <Card key={card.title} card={card} status="live" index={i} />
              ))}
            </div>
            <div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
              <Link
                href="/insights"
                className="inline-flex items-center gap-1 font-semibold text-[hsl(142_55%_62%)] hover:text-[hsl(142_55%_72%)]"
                data-testid="link-try-paste"
              >
                <Download className="w-3.5 h-3.5" /> Try the Hinge ZIP import
              </Link>
              <span className="text-white/15">·</span>
              <Link
                href="/coach"
                className="inline-flex items-center gap-1 font-semibold text-[hsl(142_55%_62%)] hover:text-[hsl(142_55%_72%)]"
                data-testid="link-try-coach"
              >
                <MessageSquare className="w-3.5 h-3.5" /> Paste a thread into Chemistry Lab
              </Link>
            </div>
          </section>

          {/* Coming Q3 2026 */}
          <section className="mb-12">
            <SectionHeader
              icon={Clock}
              eyebrow="Coming Q3 2026"
              title="The integrations queued up"
              subtitle="Each one ships when the platform's API opens at the level we need. We've already specced the data contract."
              accent="hsl(var(--brand-indigo))"
            />
            <div className="grid md:grid-cols-2 gap-4">
              {COMING.map((card, i) => (
                <Card key={card.title} card={card} status="coming" index={i} />
              ))}
            </div>
          </section>

          {/* Researching */}
          <section className="mb-12">
            <SectionHeader
              icon={FlaskConical}
              eyebrow="Researching"
              title="Open questions we're still answering"
              subtitle="These are platforms where the signal is real but the privacy contract or the API shape isn't there yet. We won't ship anything we can't honour."
              accent="hsl(43 65% 65%)"
            />
            <div className="grid md:grid-cols-3 gap-4">
              {RESEARCHING.map((card, i) => (
                <Card key={card.title} card={card} status="researching" index={i} />
              ))}
            </div>
          </section>

          {/* Why-not block */}
          <motion.div
            {...fadeUp(0.08)}
            className="rounded-2xl p-5 sm:p-6 mb-10"
            style={{
              background: "linear-gradient(135deg, hsl(248 62% 52% / 0.07), hsl(43 65% 62% / 0.05))",
              border: "1px solid hsl(248 62% 52% / 0.2)",
            }}
            data-testid="card-tos-promise"
          >
            <div className="flex items-start gap-3">
              <Shield className="w-5 h-5 text-[hsl(248_62%_62%)] flex-shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-foreground mb-1">Why we don't have all these wired today</p>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  We read every TOS before we ship. Building the bones now so the integrations land cleanly when each platform opens up. The shortcut is to scrape, lie about user agents, and apologise later. We're not doing that.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Request form */}
          <section className="mb-10">
            <RequestForm />
          </section>

          {/* Footer link back to consent center */}
          <motion.div {...fadeUp(0.1)} className="text-center text-xs text-muted-foreground">
            Already a member? Manage what's saved on the{" "}
            <Link href="/connections" className="font-semibold text-[hsl(248_62%_62%)] hover:text-[hsl(248_62%_72%)]">
              Connection Center
            </Link>
            .
          </motion.div>
        </div>
      </div>
    </AppLayout>
  );
}
