import { Router, type IRouter } from "express";
import healthRouter from "./health";
import metaRouter from "./meta";
import authRouter from "./auth";
import auditsRouter from "./audits";
import profilesRouter from "./profiles";
import messagesRouter from "./messages";
import insightsRouter from "./insights";
import waitlistRouter from "./waitlist";
import leadsRouter from "./leads";
import purchaseInterestRouter from "./purchaseInterest";
import founderRouter from "./founder";
import aiRouter from "./ai";
import claimRouter from "./claim";
import accountRouter from "./account";
import coachFollowUpsRouter from "./coachFollowUps";
import pushTokensRouter from "./push_tokens";
import lifePulseRouter from "./lifePulse";
import mirrorRouter from "./mirror";
import journalRouter from "./journal";
import postDateNotesRouter from "./postDateNotes";
import wellnessRouter from "./wellness";
import meImportsRouter from "./meImports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(metaRouter);
router.use(authRouter);
router.use(auditsRouter);
router.use(profilesRouter);
router.use(messagesRouter);
router.use(insightsRouter);
router.use(waitlistRouter);
router.use(leadsRouter);
router.use(purchaseInterestRouter);
router.use(founderRouter);
router.use(aiRouter);
router.use(claimRouter);
router.use(accountRouter);
router.use(coachFollowUpsRouter);
router.use(pushTokensRouter);
router.use(lifePulseRouter);
router.use(mirrorRouter);
router.use(journalRouter);
router.use(postDateNotesRouter);
router.use(wellnessRouter);
router.use(meImportsRouter);

export default router;
