import { Router, type IRouter } from "express";
import healthRouter from "./health";
import metaRouter from "./meta";
import authRouter from "./auth";
import auditsRouter from "./audits";
import profilesRouter from "./profiles";
import messagesRouter from "./messages";
import insightsRouter from "./insights";
import waitlistRouter from "./waitlist";
import leadsRouter from "./leads";
import purchaseInterestRouter from "./purchaseInterest";
import founderRouter from "./founder";
import aiRouter from "./ai";
import claimRouter from "./claim";
import accountRouter from "./account";
import coachFollowUpsRouter from "./coachFollowUps";
import pushTokensRouter from "./push_tokens";
import lifePulseRouter from "./lifePulse";
import mirrorRouter from "./mirror";
import companionRouter from "./companion";
import journalRouter from "./journal";
import postDateNotesRouter from "./postDateNotes";
import wellnessRouter from "./wellness";
import meImportsRouter from "./meImports";
import receiptsRouter from "./receipts";
import compassRouter from "./compass";
import importsRouter from "./imports";
import matchingRouter from "./matching";
import connectionsRouter from "./connections";
import storageRouter from "./storage";
import photosRouter from "./photos";
import journeyRouter from "./journey";
import achievementsRouter from "./achievements";
import signalMapRouter from "./signalMap";
import trustLedgerRouter from "./trustLedger";
import datingWinsRouter from "./datingWins";
import behavioralGrowthRouter from "./behavioralGrowth";
import wouldYouRatherRouter from "./wouldYouRather";
import dailySparkRouter from "./dailySpark";
import flagsRouter from "./flags";
import cosmicRouter from "./cosmic";
import verificationRouter from "./verification";
import scenariosRouter from "./scenarios";
import predictionsRouter from "./predictions";
import timeCapsulesRouter from "./timeCapsules";
import wingmanRouter from "./wingman";
import rehearsalRouter from "./rehearsal";
import referralsRouter from "./referrals";
import photoLabRouter from "./photoLab";
import eventsRouter from "./events";
import safetyRouter from "./safety";
import careDialectRouter from "./careDialect";
import connectorsRouter from "./connectors";
import devAuthRouter from "./devAuth";
import { isDevEnvironment } from "../lib/devSeed";

const router: IRouter = Router();

router.use(healthRouter);
router.use(metaRouter);
router.use(authRouter);
router.use(auditsRouter);
router.use(profilesRouter);
router.use(messagesRouter);
router.use(insightsRouter);
router.use(waitlistRouter);
router.use(leadsRouter);
router.use(purchaseInterestRouter);
router.use(founderRouter);
router.use(aiRouter);
router.use(claimRouter);
router.use(accountRouter);
router.use(coachFollowUpsRouter);
router.use(pushTokensRouter);
router.use(lifePulseRouter);
router.use(mirrorRouter);
router.use(companionRouter);
router.use(journalRouter);
router.use(postDateNotesRouter);
router.use(wellnessRouter);
router.use(meImportsRouter);
router.use(receiptsRouter);
router.use(compassRouter);
router.use(importsRouter);
router.use(matchingRouter);
router.use(connectionsRouter);
router.use(storageRouter);
router.use(photosRouter);
router.use(journeyRouter);
router.use(achievementsRouter);
router.use(signalMapRouter);
router.use(trustLedgerRouter);
router.use(datingWinsRouter);
router.use(behavioralGrowthRouter);
router.use(wouldYouRatherRouter);
router.use(dailySparkRouter);
router.use(flagsRouter);
router.use(cosmicRouter);
router.use(verificationRouter);
router.use(scenariosRouter);
router.use(predictionsRouter);
router.use(timeCapsulesRouter);
router.use(wingmanRouter);
router.use(rehearsalRouter);
router.use(referralsRouter);
router.use(photoLabRouter);
router.use(eventsRouter);
router.use(safetyRouter);
router.use(careDialectRouter);
router.use(connectorsRouter);

// Development-only test-user preview + safe test-login. Mounted only outside
// production; the router additionally 404s every request in production as a
// second guard. Never reachable in a deployed build.
if (isDevEnvironment()) {
  router.use(devAuthRouter);
}

export default router;
