kind = "mobile"
previewPath = "/mobile/"
title = "NLDC Mobile"
version = "1.0.0"
id = "artifacts/nldc-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 23790

[services.development]
run = "pnpm --filter @workspace/nldc-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nldc-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/nldc-mobile", "run", "serve" ]

[services.env]
PORT = "23790"
BASE_PATH = "/mobile/"
